# Absences and Makeup Policies

## Excused Absences

[University policy](https://policy.umn.edu/education/makeupwork) recognizes that there are a variety of legitimate circumstances in which students will miss coursework, and that accommodations for makeup work will be made. These situations generally fall into several categories:

- illness, physical or mental, of the student or a student’s dependent;
- medical conditions related to pregnancy;
- participation in intercollegiate athletic events;
- subpoenas;
- jury duty;
- military service;
- bereavement, including travel related to bereavement;
- religious observances;
- participation in formal University system governance, including the University Senate, Student Senate, and Board of Regents meetings, by students selected as representatives to those bodies;
- taking college entrance exams (PSAT, ACT, SAT) for Post-Secondary Enrollment Option (PSEO) students that are provided at their high school; and
- activities sponsored by the University if identified by the senior academic officer for the campus or the officer’s designee as the basis for excused absences.

These absences should be pre-coordinated with the instructor as soon as they are known - in emergency or unexpected situation, communication may occur after the fact. **All other absences are considered unexcused absences**

## Makeup Policies for Unexcused Absences

*Weekly Quiz Part I:* If you miss Part I of the weekly quiz you will receive a 2 pt deduction. You can still complete Part I of the quiz for 3/5 pts, however! Your completed Part I quiz must be turned in by 11:59PM on Wednesday of the following week.

*Weekly Quiz Part II:* If you miss Part II of the weekly quiz you will receive a 2 pt deduction. You can still complete the quiz for 13/15 pts, however! Your Part II quiz must be turned in by 11:59PM on Friday of the following week to receive a grade.

*Discussion Collaborative Exercises:* Discussion exercises are team activities. If you miss discussion you will receive a 2 pt deduction. You can still complete the exercise for 4/6 pts, however. Your completed exercise must be turned in by the beginning of discussion the following week to receive a grade.

*Land-Use Reports:* Deduct 11% for every 24 hour period late.

*Exams:* No exam make-ups for unexcused absences.
